### ISSUE TITLE
Feature request: Save Descriptor to SD card (and recover it from SD)

### ISSUE THREAD

**Issue by bitcoinheiro** [odudex/krux#11]
After importing a multisig descriptor (or any descriptor) via QR would be great if there would be an option to save it to the microSD in a standard format for importing to other devices/coordinators and/or back to krux when/if needed.

This way I don't need to scan it from the coordinator every time I want to check an address of a multisig wallet.

**Comment by odudex** [comment]
Good idea, we could display it and add the options to save on flash, SD card or print, so user can choose, like it's done with encrypted mnemonics. I Know you don't like the internal flash, and yes SD card is easier to hide, but remember SD card is also flash, just in format that is much easier to extract/tamper data.

**Comment by bitcoinheiro** [comment]
Yes, agree. Would be nice to just be able to have the descriptor available for quick recovery if needed.
I only like the SD card because, if user is careful, he/she can hide it separate from the device to increase deniability in case of physical attack. Internal flash is cool too, if able to encrypt the data (optional), even better
