### ISSUE TITLE
Text after PSBT signing goes away without user input

### ISSUE THREAD

**Issue by hugoender** [odudex/krux#2]
After you sign psbt, some text comes up and then goes away without user input. I was unable to read it before it went away. Consider making it so that it stays on screen until user presses a button. Using M5stickV.

**Comment by odudex** [comment]
Do you mean when saving the signed PSBT on SD card? "Saved PSBT to SD card: <psbt_filename>"

**Comment by hugoender** [comment]
Yes, that is correct. It shows that page for a second or two and then goes away.

**Comment by odudex** [comment]
Solved with 080c826855dba8d86b21cb0c028848223b577865
